version: '3.9'

services:
    backend:
      build:
        context: ./backend
      image: backend-event-image
      env_file:
        - ./backend/.env
      healthcheck:
        test: ["CMD", "curl", "--fail", "http://localhost:8000/api/openapi"]
        interval: 15s
        timeout: 5s
        retries: 5
      expose:
        - 8000
      depends_on:
        rabbit:
          condition: service_healthy

    rabbit:
      image: rabbitmq:3-management
      container_name: rabbit
      ports:
        - 5672:5672
        - 15672:15672
        - 25672:25672
      healthcheck:
        test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
        interval: 10s
        timeout: 5s
        retries: 30

    nginx:
      image: nginx:1.23.4-alpine
      volumes:
        - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./backend/configs/nginx:/etc/nginx/conf.d:ro
        - ./backend/tmp/logs/nginx/:/var/log/nginx/
      depends_on:
        backend:
          condition: service_healthy
      ports:
        - "80:80"
      logging:
        driver: gelf
        options:
          gelf-address: udp://127.0.0.1:5044
          tag: nginx 

    logstash:
      image: logstash:7.10.1
      environment:
        ES_HOST: "elasticsearch:9200"
      volumes:
        - ./backend/configs/logstash.conf:/config/logstash.conf:ro
        - ./backend/tmp/logs/nginx/:/var/log/nginx/:ro
      command: logstash -f /config/logstash.conf 

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
      environment:
        discovery.type: single-node
      volumes:
        - ./tmp/esdata:/tmp/elasticsearch/data
      
    kibana:
      image: docker.elastic.co/kibana/kibana:7.10.2
      depends_on:
        - elasticsearch

    filebeat:
      image: elastic/filebeat:7.3.2
      volumes:
        - ./tmp/logs/nginx:/var/log/nginx:ro
        - ./backend/configs/filebeat.yml:/usr/share/filebeat/filebeat.yml
      depends_on:
        - backend
        - nginx
        - logstash
        - elasticsearch
        - kibana
      links:
        - logstash

    enricher:
      build:
        context: ./enricher
      env_file:
        - ./enricher/.env
      depends_on:
        rabbit:
          condition: service_healthy

