[tool.flake8]
exclude = ['.git', '__pycache__', 'venv', 'storage_research']
max-complexity = 10
max-line-length = 88

[tool.isort]
line_length = 88
profile = "black"
py_version = 310

[tool.pyright]
exclude = [
    "**/__pycache__"
]
include = [
  "backend",
]
pythonPlatform = "All"
pythonVersion = "3.10"
typeCheckingMode = "basic"
useLibraryCodeForTypes = true
venv = "venv"
venvPath = '.'

[tool.pytest.ini_options]
pythonpath = "."
