name: Python application

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10.12]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r backend/requirements.txt

    - name: Lint with flake8
      run: flake8

    - name: Check with pyright
      run: |
        pyright backend/src/

    - name: Running tests in Docker Compose
      id: test
      run: docker-compose -f backend/tests/functional/docker-compose.yml up --exit-code-from tests

    - name: Send Telegram notification on success or failure
      if: always()
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        MESSAGE="$REPO_NAME: Pipeline for $GITHUB_SHA finished "
        if [ ${{ job.status }} == 'success' ]; then
          MESSAGE+="successfully! 🎉"
        else
          MESSAGE+="with error."
          FAILED_STEP_NAME="${{ steps.test.outcome }}"
          MESSAGE+=" Failed step: $FAILED_STEP_NAME"
        fi
        curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d "chat_id=$TELEGRAM_CHAT_ID" \
          -d "text=$MESSAGE"
